const languages = {
2. Spanish: `es`
3. French: `fr`
4. German: `de`
5. Italian: `it`
6. Portuguese: `pt`
7. Dutch: `nl`
8. Russian: `ru`
9. Chinese (Simplified): `zh`
10. Japanese: `ja`
11. Korean: `ko`
12. Arabic: `ar`
13. Hindi: `hi`
14. Turkish: `tr`
15. Greek: `el`
16. Swedish: `sv`
17. Norwegian: `no`
18. Danish: `da`
19. Finnish: `fi`
20. Polish: `pl`
21. Hungarian: `hu`
22. Czech: `cs`
23. Thai: `th`
24. Hebrew: `he`
25. Indonesian: `id`
26. Malay: `ms`
27. Vietnamese: `vi`
28. Romanian: `ro`
29. Ukrainian: `uk`
30. Bulgarian: `bg`
31. Croatian: `hr`
32. Serbian: `sr`
33. Slovak: `sk`
34. Slovenian: `sl`
35. Lithuanian: `lt`
36. Latvian: `lv`
37. Estonian: `et`
38. Bengali: `bn`
39. Tamil: `ta`
40. Telugu: `te`
41. Urdu: `ur`
42. Punjabi: `pa`
43. Gujarati: `gu`
44. Marathi: `mr`
45. Kannada: `kn`
46. Malayalam: `ml`
47. Sinhala: `si`
48. Nepali: `ne`
49. Swahili: `sw`
50. Filipino: `fil`
}; module.exports = languages;
